/**
 * What the restaurant can offer, worked out from the same opening hours and
 * floor plan the site draws — `reservation-data.json`, generated by
 * `npm run sync:data`.
 */
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { root } from './env.js'

const data = JSON.parse(readFileSync(resolve(root, 'reservation-data.json'), 'utf8'))

export const { openingHours, reservation: rules, tables, zones } = data
export const tableById = new Map(tables.map((table) => [table.id, table]))

const pad = (value) => String(value).padStart(2, '0')
const toMinutes = (time) => {
  const [h, m] = time.split(':').map(Number)
  return h * 60 + m
}
const fromMinutes = (minutes) => `${pad(Math.floor(minutes / 60))}:${pad(minutes % 60)}`

/** Parses "YYYY-MM-DD" as a local date — `new Date(iso)` would shift it. */
export function parseISODate(iso) {
  const [y, m, d] = iso.split('-').map(Number)
  return new Date(y, m - 1, d)
}

export const toISODate = (date) =>
  `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`

export const hoursFor = (day) => openingHours[String(day)] ?? null

/** Every seating time offered on a date, empty on a day the kitchen is closed. */
export function slotsForDate(iso) {
  const hours = hoursFor(parseISODate(iso).getDay())
  if (!hours) return []

  const first = toMinutes(hours[0])
  const last = toMinutes(hours[1]) - rules.lastSeatingBeforeClose
  const slots = []
  for (let m = first; m <= last; m += rules.slotMinutes) slots.push(fromMinutes(m))
  return slots
}

/**
 * The tables staff would push together for this party, starting from one of
 * them — the same walk over `joinsWith` the site does, so both ends agree on
 * what can be offered.
 */
export function resolveTableGroup(primaryId, partySize, isFree) {
  const primary = tableById.get(primaryId)
  if (!primary || primary.disabled || !isFree(primary.id)) return null

  const group = [primary]
  const taken = new Set([primary.id])
  let seats = primary.seats

  while (seats < partySize) {
    const nextId = group
      .flatMap((table) => table.joinsWith ?? [])
      .find((id) => !taken.has(id) && isFree(id) && !tableById.get(id)?.disabled)
    if (!nextId) return null

    const next = tableById.get(nextId)
    if (!next) return null
    taken.add(nextId)
    group.push(next)
    seats += next.seats
  }

  return group.map((table) => table.id)
}

/** Can this party be seated anywhere, given what is already booked? */
export function seatsAnyone(partySize, taken) {
  const isFree = (id) => !taken.has(id) && !tableById.get(id)?.disabled
  return tables.some((table) => Boolean(resolveTableGroup(table.id, partySize, isFree)))
}

/** Labels the way the restaurant says them: "4, 1". */
export const labelsOf = (ids) =>
  ids.map((id) => tableById.get(id)?.label ?? id).join(', ')

/** The room a booking sits in, in Polish. */
export const zoneOf = (ids) => {
  const zone = tableById.get(ids[0] ?? '')?.zone
  return zone ? (zones[zone] ?? '') : ''
}
